system:
  type: linux
  max_agents: 4
  max_memory_gb: 6
  enable_gpu: false
  gpu_priority: false

game:
  name: "Ghost: Black Ops"
  version: "1.0.0"
  target_platforms: ["ubuntu", "windows"]

ai:
  model_provider: "openai"
  max_concurrent_tasks: 2
  enable_learning: true
  training_interval: 3600

unity:
  project_path: "./unity_project"
  assets_path: "./unity_project/Assets"
  scripts_path: "./unity_project/Assets/Scripts"

performance:
  texture_quality: "medium"
  shadow_quality: "low"
  anti_aliasing: "fxaa"
  target_fps: 60

development:
  auto_save: true
  backup_interval: 300
  version_control: true
